variables:
  MAVEN_OPTS: "-Dhttps.protocols=TLSv1.2 -Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=WARN -Dorg.slf4j.simpleLogger.showDateTime=true -Djava.awt.headless=true"
  MAVEN_CLI_OPTS: "--batch-mode --errors --fail-at-end --show-version -DinstallAtEnd=true -DdeployAtEnd=true"

cache:
  paths:
  - .m2/repository

stages:
  - build
  - test
  - deploy
  - pages

before_script:
- 'gpg -v --import <(echo "$GPG_PRIVATE_KEY" | base64 -d)'

.validate: &validate
  stage: build
  script:
  - 'mvn $MAVEN_CLI_OPTS test-compile'

.verify: &verify
  stage: test
  script:
  - 'mvn $MAVEN_CLI_OPTS verify site site:stage'
  after_script:
  - bash <(curl -s https://codecov.io/bash) -t "${CODECOV_TOKEN}"
  except:
  - master
  - hotfix/1.0.0-rc.1
  artifacts:
    reports:
      junit:
      - target/surefire-reports/TEST-*.xml
      - target/failsafe-reports/TEST-*.xml

# Validate merge requests using JDK7
validate:jdk7:
  <<: *validate
  image: maven:3.3.9-jdk-7

# Validate merge requests using JDK8
validate:jdk8:
  <<: *validate
  image: maven:3.3.9-jdk-8

# Verify merge requests using JDK7
verify:jdk7:
  <<: *verify
  image: maven:3.3.9-jdk-7

# Verify merge requests using JDK8
verify:jdk8:
  <<: *verify
  image: maven:3.3.9-jdk-8

deploy:jdk8:
  stage: deploy
  script:
  - 'cp .gitlab/settings.xml /root/.m2/settings.xml'
  - 'sed -i "s/${CI_JOB_TOKEN}/${CI_JOB_TOKEN}/g" /root/.m2/settings.xml'
  - 'mvn $MAVEN_CLI_OPTS clean deploy site site:stage -DskipTests=true -B -U'
  only:
  - master
  - hotfix/1.0.0-rc.1
  # Archive up the built documentation site.
  artifacts:
    paths:
    - target/staging
  image: maven:3.3.9-jdk-8

pages:
  image: busybox:latest
  stage: pages
  script:
  # Because Maven appends the artifactId automatically to the staging path if you did define a parent pom,
  # you might need to use `mv target/staging/YOUR_ARTIFACT_ID public` instead.
  - mv target/staging public
  dependencies:
  - deploy:jdk8
  artifacts:
    paths:
    - public
  only:
  - master